In [ ]:
# 사과나무 (다이아몬드) ---------- 인덱스 문제
# 현수의 농장은 N X N 격자판으로 이루어져 있으며, 각 격자안에는 한 그루의 사과나무가 심어져 있다.
# N의 크기는 항상 홀수이다. 가을이 되어 사과를 수확해야 하는데 현수는 격자판안의 사과를 수확할 때
# 다이아몬드 모양의 격자판만 수확하고 나머지 격자안의 사과는 새들을 위해서 남겨놓는다.
# 만약 N이 5이면 아래 그림과 같이 진한 부분의 사과를 수확한다.
# 3X3 으로 쪼개서 생각한다. 첫번째 줄은 가운데 인덱스를 구한다.
# 사과나무in1.txt. -> 1049 , 사과나무in2.txt -> 1991
# 마방진 인덱스문제 찾아서 풀어보자..

In [18]:
temp = []
with open('사과나무in2.txt', 'r') as f:
    
    n = int(f.readline())
    a = [list(map(int, f.readline().split())) for _ in range(n)]
    sum = 0
    s=e=n//2  
    for i in range(n):        
        for j in range(s, e+1):
            sum += a[i][j]
        if i < n // 2:
            s -= 1; e += 1
        else:
            s+=1; e-=1
    print(sum)

    

1991


In [9]:
x = "3 6 9"
y = x.split(' ')
print(y)
x.split()

['3', '6', '9']


In [24]:
abc, _ = 3, 4  # 필요없는 값을 담을 필요 없을 때 _

In [52]:
# 선생님 버전
with open("사과나무in3.txt", 'r') as f:
    n = int(f.readline())
    a = [list(map(int, f.readline().split())) for _ in range(n)] # i 를 인덱스로 활용안하기때문에 변수낭비하지않기위해 _ 사용

    sum = 0
    s=e=n//2 # 시작은 s index, 마지막은 e index
    for i in range(n):
        for j in range(s, e+1):
            sum = sum + a[i][j]
        if i < n // 2:
            s = s - 1; e = e + 1         
        else:
            s = s + 1; e = e - 1
    print(sum)

20


In [20]:
a

[[1, 5, 9], [4, 3, 2], [2, 6, 6]]

In [22]:
a[0][1], a[1][0],a[1][1], a[1][2], a[2][1]

(5, 4, 3, 2, 6)

In [23]:
n

3

In [32]:
temp = []
for i in a:
    for j in range(len(a)):
        pass
    print(i)


[1, 5, 9]
[4, 3, 2]
[2, 6, 6]


In [43]:
#선생님 버전
def N_matrix(n):
    import random
    random.seed(0) # 랜덤결과를 다른 프로그램에서도 동일하게 나온다.
    return [[random.randint(1, n*n) for i in range(n)] for j in range(n)]

In [46]:
X = 3
m1 = N_matrix(X)
for i in range(X):
    print(m1[i])

[7, 7, 1]
[5, 9, 8]
[7, 5, 8]


# 마방진은 자연수를 정사각형 모양으로 나열했을때 가로, 세로, 대각선의 합이 전부 같은 형태의 배열
## 마방진 구하기 3X3 부터...
# N*N Matrix 마방진을 만들어보세요..
# N은 홀수로 입력 받는다. N은 3이상이다.
# 가로, 세로, 대각선의 합이 같은 매트릭스를 만드시오



In [60]:
import numpy as np
n = int(input("n*n 마방진을 위한 n값을 입력(3이상, 홀수만)>>"))
matrix = np.zeros((n,n), dtype=int)
matrix
s_row=0; s_col=n//2
matrix[s_row, s_col]=1
row=0; col=0

for i in range(2, n * n + 1):
    row = s_row # 전 위치값 row값 보관
    col = s_col # 전 위치 col값 보관
    
    s_row  = s_row - 1; s_col = s_col + 1
    if s_row < 0 :
        s_row = n - 1 
    if s_col > n - 1:
        s_col = 0
        
    if matrix[s_row, s_col] == 0 :
        matrix[s_row, s_col] = i
    else: # 0이 아니면 다른 숫자가 있다
        s_row = row + 1; s_col = col
        matrix[s_row, s_col] = i

print(matrix)

n*n 마방진을 위한 n값을 입력(3이상, 홀수만)>>7
[[30 39 48  1 10 19 28]
 [38 47  7  9 18 27 29]
 [46  6  8 17 26 35 37]
 [ 5 14 16 25 34 36 45]
 [13 15 24 33 42 44  4]
 [21 23 32 41 43  3 12]
 [22 31 40 49  2 11 20]]
