In [5]:
a = [1,2, ['a','b',['Life','is']]]

In [6]:
a[2][2][0]

'Life'

In [3]:
import numpy as np

In [4]:
np.random.seed(42)
arr1=np.random.randint(1,10,(3,4))

In [5]:
arr1

array([[7, 4, 8, 5],
       [7, 3, 7, 8],
       [5, 4, 8, 8]])

In [10]:
arr1.sum()

74

In [12]:
np.sum(arr1)

74

In [109]:
a = list(range(1,11))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [108]:
# list(map(lambda x: x>3 and x<8, a))
list(filter(lambda x: x>3 and x<8, a))

[4, 5, 6, 7]

In [13]:
np.random.seed(42)
x = np.random.randint(1,12,(4,4))

In [14]:
x

array([[ 7,  4, 11,  8],
       [ 5,  7, 10,  3],
       [ 7, 11, 11,  8],
       [ 5,  4,  8,  8]])

In [15]:
(x > 5) & (x < 10)  # condition 만 들어가면 true & false

array([[ True, False, False,  True],
       [False,  True, False, False],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [16]:
x[(x > 5) & (x < 10)] # fancy indexing 기법 (트루값을 뽑아낸다.) ***

array([7, 8, 7, 7, 8, 8, 8])

In [17]:
np.sum((x > 5) & (x < 10), axis=0) #  True 값을 1로 간주하여 합을 구한다.

array([2, 1, 1, 3])

In [18]:
np.sum((x > 5) & (x < 10), axis=1).reshape(4, 1)

array([[2],
       [1],
       [2],
       [2]])

In [33]:
x=np.arange(64).reshape(4, 16)

In [34]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [35]:
[ list(range(i, i+8)) for i in range(8)]

[[0, 1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [2, 3, 4, 5, 6, 7, 8, 9],
 [3, 4, 5, 6, 7, 8, 9, 10],
 [4, 5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [6, 7, 8, 9, 10, 11, 12, 13],
 [7, 8, 9, 10, 11, 12, 13, 14]]

In [36]:
x=np.arange(120).reshape(6, -1) # 자동으로 배열을 만들때 -1

In [37]:
x

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119]])

In [38]:
x.shape

(6, 20)

In [39]:
x= np.arange(100).reshape(10, 10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
x[5][3:6]   

array([53, 54, 55])

In [44]:
x[8][[2,4,8]] # <=== 이런방식도 Fancy indexing

array([82, 84, 88])

In [46]:
x[9][9]

99

In [56]:
np.random.seed(52)
x=np.array(np.random.randint(55, size=10))
x

array([53, 28, 11, 13, 23, 22, 28, 32,  5, 42])

In [57]:
idx = np.argsort(x) # x 의 인덱스 번호로 정렬한 배열 값 *************

In [58]:
idx

array([8, 2, 3, 5, 4, 1, 6, 7, 9, 0], dtype=int64)

In [59]:
for i in idx:
    print(x[i], end = " ")

5 11 13 22 23 28 28 32 42 53 

In [67]:
print(x[[8, 2, 3, 5, 4, 1, 6, 7, 9, 0]])
print(x[idx]) # <=== fancy indexing
print(x[np.argsort(x)])

[ 5 11 13 22 23 28 28 32 42 53]
[ 5 11 13 22 23 28 28 32 42 53]
[ 5 11 13 22 23 28 28 32 42 53]


In [70]:
print(np.argmax(x)) # <== 가장 큰값의 index
print(np.argmin(x)) # <== 가장 작은값의 index

0
8


In [77]:
a=np.array([[3,2],[6,8]])
b=np.array([[6],[4]])
print(a)
print(b)
print(a.shape)
print(b.shape)

[[3 2]
 [6 8]]
[[6]
 [4]]
(2, 2)
(2, 1)


In [78]:
np.dot(a, b)          # <==== 행렬 곱 dot()

array([[26],
       [68]])

In [87]:
ar = np.arange(6).reshape(2,3)
print(ar)
ar.shape

[[0 1 2]
 [3 4 5]]


(2, 3)

In [83]:
print(ar.T)  # <===  T 행과 열을 바꿔준다.
ar.T.shape

[[0 3]
 [1 4]
 [2 5]]


(3, 2)

In [86]:
print(np.dot(ar, ar.T).shape)   # <==== 행과 열을 바꾼궛과 원본을 곱하면 정방행렬이된다.
np.dot(ar, ar.T)

(2, 2)


array([[ 5, 14],
       [14, 50]])

In [100]:
# 2차원 배열 슬라이싱
arr = np.arange(64).reshape(4,16)
xx = np.dot(arr, arr.T)
print(xx)
xy = xx[0:3, 1:]


[[ 1240  3160  5080  7000]
 [ 3160  9176 15192 21208]
 [ 5080 15192 25304 35416]
 [ 7000 21208 35416 49624]]


In [102]:
print(xy[0][2]) # <== 리스트 O, numpy O
print(xy[0, 2]) # <== 리스트에선 지원안됨 numpy에;서만

7000
7000


In [95]:
# 슬라이싱
xx = np.arange(12).reshape(3,4)
print(xx)
xx[0:, 1:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])