In [2]:
import numpy as np

In [3]:
ar = np.random.random((2,2,4))
ar

array([[[0.85467445, 0.26354869, 0.25981055, 0.28136598],
        [0.60033496, 0.82147648, 0.25887798, 0.14438078]],

       [[0.52615032, 0.03514731, 0.92205535, 0.7705099 ],
        [0.4959961 , 0.79251234, 0.38519925, 0.47650701]]])

In [4]:
np.argmin(ar)

9

In [5]:
a = np.array([[3,2,-1],[0,2,4]])
b = np.array([[2,2],[3,4],[5,1]])
a@b

array([[ 7, 13],
       [26, 12]])

In [6]:
c = np.array([[1,9],[3,4],[2,4]])
d =  np.array([[1,4,-1], [7,1,4]])
c@d

array([[64, 13, 35],
       [31, 16, 13],
       [30, 12, 14]])

In [7]:
X = np.arange(1,11,0.1).reshape(10, -1)

In [8]:
X

array([[ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9],
       [ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9],
       [ 3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9],
       [ 4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9],
       [ 5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9],
       [ 6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9],
       [10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9]])

In [16]:
X.shape

(10, 10)

In [17]:
np.random.seed(42)
ar = np.random.random(size=(3,5,6))
ar

array([[[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
         0.15599452],
        [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
         0.96990985],
        [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
         0.52475643],
        [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
         0.36636184],
        [0.45606998, 0.78517596, 0.19967378, 0.51423444, 0.59241457,
         0.04645041]],

       [[0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
         0.80839735],
        [0.30461377, 0.09767211, 0.68423303, 0.44015249, 0.12203823,
         0.49517691],
        [0.03438852, 0.9093204 , 0.25877998, 0.66252228, 0.31171108,
         0.52006802],
        [0.54671028, 0.18485446, 0.96958463, 0.77513282, 0.93949894,
         0.89482735],
        [0.59789998, 0.92187424, 0.0884925 , 0.19598286, 0.04522729,
         0.32533033]],

       [[0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
         0.542696

In [10]:
A = np.arange(1,9).reshape(2,4)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
B = np.arange(1,9).reshape(4,2)
B

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
A@B == np.dot(A,B)

array([[ True,  True],
       [ True,  True]])

In [20]:
A*3 # 브로드캐스팅으로 동작한다.

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]])

In [21]:
A*A

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [24]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr2 = np.arange(1,13).reshape(2,2,3)
arr2.ndim

3

In [31]:
np.random.randint(8,19, size=5)

array([13, 12, 14, 17, 14])

In [32]:
np.arange(10,100,10).reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [33]:
np.random.randint(10, 100, size=(3,2,3))

array([[[15, 80, 71],
        [64, 92, 22]],

       [[46, 49, 77],
        [10, 12, 23]],

       [[77, 89, 84],
        [50, 77, 56]]])

In [34]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [42]:
np.random.random((2,5,3))

array([[[0.71755698, 0.73660491, 0.773441  ],
        [0.75861687, 0.57241182, 0.3506142 ],
        [0.43135705, 0.6134431 , 0.14605343],
        [0.21982352, 0.52647769, 0.78290819],
        [0.3248737 , 0.02314633, 0.55757681]],

       [[0.35822138, 0.40864811, 0.56082525],
        [0.23338749, 0.35608394, 0.93296929],
        [0.16797432, 0.66240204, 0.26199534],
        [0.30189809, 0.25792549, 0.53787233],
        [0.50760333, 0.1266129 , 0.86567364]]])

In [43]:
np.arange(10,25).reshape(3,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
np.arange(11,61).reshape(2,5,5)

array([[[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [46]:
np.arange(74,250,5).reshape(3,3,4)

array([[[ 74,  79,  84,  89],
        [ 94,  99, 104, 109],
        [114, 119, 124, 129]],

       [[134, 139, 144, 149],
        [154, 159, 164, 169],
        [174, 179, 184, 189]],

       [[194, 199, 204, 209],
        [214, 219, 224, 229],
        [234, 239, 244, 249]]])

In [48]:
np.arange(10).reshape(2,5).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [51]:
ar = np.arange(12).reshape(3,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
ar[1:2, 1:2 ]

array([[5]])

In [60]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
arr[1:,1:]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [62]:
ar1 = np.arange(24).reshape(3,2,4)
ar1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [64]:
ar1[1:, 1:, :1]

array([[[12]],

       [[20]]])

In [65]:
ar1[1:, 0:, :3]

array([[[ 8,  9, 10],
        [12, 13, 14]],

       [[16, 17, 18],
        [20, 21, 22]]])

In [73]:
ar1[1:3, 1:3, 1:]

array([[[13, 14, 15]],

       [[21, 22, 23]]])

In [74]:
ar1 * 3

array([[[ 0,  3,  6,  9],
        [12, 15, 18, 21]],

       [[24, 27, 30, 33],
        [36, 39, 42, 45]],

       [[48, 51, 54, 57],
        [60, 63, 66, 69]]])

In [75]:
np.array([7,5,9,10]) * 3

array([21, 15, 27, 30])

In [76]:
np.array([4, 10, 6, 2]) * 3

array([12, 30, 18,  6])

In [84]:
a = np.array([[7,5,9,10],[4, 10, 6, 2]])
b = np.array([[1,3,4,9],[14,7,6,4]])

a-b

array([[  6,   2,   5,   1],
       [-10,   3,   0,  -2]])

In [85]:
np.array(list(map(lambda x: x > 0, a-b)))

array([[ True,  True,  True,  True],
       [False,  True, False, False]])

In [87]:
a.sum(axis=1)

array([31, 22])