In [1]:
a=[1,2,['a','b',['Life','is']]]

In [5]:
import numpy as np

In [8]:
np.random.seed(42)
arr1=np.random.randint(1,10,(3,4))

In [9]:
arr1

array([[7, 4, 8, 5],
       [7, 3, 7, 8],
       [5, 4, 8, 8]])

In [10]:
arr1.sum()

74

In [11]:
np.sum(arr1)

74

In [12]:
np.sum(arr1, axis=0)

array([19, 11, 23, 21])

In [27]:
np.sum(arr1, axis=1).reshape(3,1)

array([[24],
       [25],
       [25]])

In [26]:
X.reshape(3,1)

array([[24],
       [25],
       [25]])

In [28]:
np.random.seed(42)
X=np.random.randint(1,12,(4,4))

In [29]:
X

array([[ 7,  4, 11,  8],
       [ 5,  7, 10,  3],
       [ 7, 11, 11,  8],
       [ 5,  4,  8,  8]])

In [30]:
(X > 5) & ( X <10 )

array([[ True, False, False,  True],
       [False,  True, False, False],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [35]:
X[(X > 5) & ( X <10 )]  # fancy indexing 기법이라고 한다.

array([7, 8, 7, 7, 8, 8, 8])

In [36]:
np.sum((X > 5) & ( X <10 ), axis=0) # True 값을 1로 간주하여 합을 구한다. 

array([2, 1, 1, 3])

In [37]:
np.sum((X > 5) & ( X <10 ), axis=1).reshape(4,1)

array([[2],
       [1],
       [2],
       [2]])

In [59]:
X=np.arange(100).reshape(10,-1)

In [60]:
X.shape

(10, 10)

In [61]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [63]:
X[5][3:6]

array([53, 54, 55])

In [65]:
X[8][[2,4,8]]  # <=== 요렇게 접근하는 방식을 Fancy indexing 이라고 한다. 

array([82, 84, 88])

In [64]:
X[8][2], X[8][4], X[8][8]

(82, 84, 88)

In [66]:
X[9][9]

99

In [72]:
np.random.seed(52)
X=np.array(np.random.randint(55, size=10))

In [73]:
X

array([53, 28, 11, 13, 23, 22, 28, 32,  5, 42])

In [77]:
idx = np.argsort(X)

In [78]:
idx

array([8, 2, 3, 5, 4, 1, 6, 7, 9, 0], dtype=int64)

In [75]:
for i in idx:
    print(X[i], end=" ")

5 11 13 22 23 28 28 32 42 53 

In [81]:
X[np.argsort(X)]

array([ 5, 11, 13, 22, 23, 28, 28, 32, 42, 53])

In [84]:
X

array([53, 28, 11, 13, 23, 22, 28, 32,  5, 42])

In [83]:
np.argmax(X)

0

In [85]:
np.argmin(X)

8

In [96]:
A=np.array([[3,2],[6,8]])

In [105]:
A*B

array([[18, 12],
       [24, 32]])

In [106]:
np.dot(A,B)

array([[26],
       [68]])

In [103]:
B=np.array([[6],[4]])

In [104]:
B.shape

(2, 1)

In [117]:
ar = np.arange(64).reshape(4,16)

In [118]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [119]:
ar.T

array([[ 0, 16, 32, 48],
       [ 1, 17, 33, 49],
       [ 2, 18, 34, 50],
       [ 3, 19, 35, 51],
       [ 4, 20, 36, 52],
       [ 5, 21, 37, 53],
       [ 6, 22, 38, 54],
       [ 7, 23, 39, 55],
       [ 8, 24, 40, 56],
       [ 9, 25, 41, 57],
       [10, 26, 42, 58],
       [11, 27, 43, 59],
       [12, 28, 44, 60],
       [13, 29, 45, 61],
       [14, 30, 46, 62],
       [15, 31, 47, 63]])

In [124]:
X=np.dot(ar,ar.T)

In [125]:
X

array([[ 1240,  3160,  5080,  7000],
       [ 3160,  9176, 15192, 21208],
       [ 5080, 15192, 25304, 35416],
       [ 7000, 21208, 35416, 49624]])

In [127]:
X=X[0:3,1:4]

In [132]:
X[0,2]

7000

In [92]:
A=np.array([[3,2],[6,8]])
B=np.array([[6],[4]])

In [93]:
A*B

array([[18, 12],
       [24, 32]])

In [94]:
B

array([[6],
       [4]])

In [95]:
np.dot(A,B)

array([[26],
       [68]])

In [32]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [34]:
list(filter(lambda x: x > 3 and x <8, a))

[4, 5, 6, 7]